"""The contract is the artifact everything else is derived from, and it moved.

a2-i2c: `contract.json` is regenerated by the architect on every run, the
witness is held forever, and one run's contract dropped `busy` from the outputs
while the next kept it. The held witness had no `busy` to emit, so every oracle
reading it abstained, the stimulus loop spent its budget, and six requirements
were ABANDONED as "never reached" -- a witness defect charged to the stimulus,
through three gates that each looked and saw nothing wrong.

Each gate below closes one of those.
"""

from __future__ import annotations

import json

from specflow.refmodel.validate import validate_source

CONTRACT = {
    "module_name": "m",
    "io": [
        {"name": "clk", "dir": "input", "width": 1},
        {"name": "a", "dir": "input", "width": 1},
        {"name": "y", "dir": "output", "width": 1},
        {"name": "busy", "dir": "output", "width": 1},
    ],
    "clocking": {"clock": {"name": "clk", "edge": "posedge"}},
}

COMPLETE = """\
from specflow.refmodel.base import RefModel


class Model(RefModel):
    OUTPUT_PORTS = ['y', 'busy']
    LATENCY_CYCLES = 0

    def step(self, i):
        return {'y': i['a'] & 1, 'busy': (i['a'] ^ 1) & 1}
"""

DROPS_BUSY = COMPLETE.replace(
    "OUTPUT_PORTS = ['y', 'busy']", "OUTPUT_PORTS = ['y']").replace(
    ", 'busy': (i['a'] ^ 1) & 1", "")


def _issues(source, tmp_path):
    return validate_source(
        source=source, requirements=[{"uid": "REQ-0000", "text": "t"}],
        contract=CONTRACT, expected_base="step", workdir=tmp_path,
        coverage={"REQ-0000": ["step"]})


def test_a_model_that_drops_a_contract_OUTPUT_is_an_error(tmp_path):
    """The one the run needed and did not have.

    Every other check in G4 asks whether the model is self-consistent -- does it
    write what it declares, do the outputs move, is it deterministic. A model
    that simply OMITS a contract output passes all of them, because the missing
    port is absent from both sides of every comparison.
    """
    errs = [i for i in _issues(DROPS_BUSY, tmp_path) if i.severity == "error"]
    assert any("busy" in i.message for i in errs), [i.message for i in errs]
    assert any("abstain" in i.message for i in errs), (
        "the error must say WHY it matters -- an oracle reading a port that is "
        "never in a row can only abstain, and that is indistinguishable from a "
        "stimulus that never reached the scenario")


def test_a_complete_model_passes_the_same_gate(tmp_path):
    errs = [i for i in _issues(COMPLETE, tmp_path)
            if i.severity == "error" and "OUTPUT_PORTS" in i.path]
    assert not errs, [i.message for i in errs]


def test_a_model_declaring_a_port_the_contract_does_not_is_also_an_error(tmp_path):
    """Both directions. The two disagreeing about the interface is the defect;
    which side is right is not something this gate can know."""
    extra = COMPLETE.replace("['y', 'busy']", "['y', 'busy', 'ghost']")
    errs = [i for i in _issues(extra, tmp_path) if i.severity == "error"]
    assert any("ghost" in i.message for i in errs), [i.message for i in errs]


# ------------------------------------------------- the held witness

def test_a_witness_whose_ports_disagree_is_not_reused():
    from specflow.oracles_stage import _ports_agree

    cj = json.dumps(CONTRACT)
    assert _ports_agree(COMPLETE, cj) is True
    assert _ports_agree(DROPS_BUSY, cj) is False


def test_an_unreadable_witness_is_still_reused():
    """A bound that disappears because a helper could not parse something is
    worse than the drift it was guarding against: it silently re-pays for a
    witness on every run where this cannot answer."""
    from specflow.oracles_stage import _ports_agree

    cj = json.dumps(CONTRACT)
    assert _ports_agree("def (", cj) is True
    assert _ports_agree(COMPLETE, "not json") is True
    assert _ports_agree("class M:\n    pass\n", cj) is True


# ------------------------------------------------- the spec's own header

DANGLING = """\
module i2c (
    input      [ 3:0] cmd,      // command
           cmd_ack,  // command complete acknowledge
           busy,     // i2c bus busy

    input             din,
           dout,

    output            scl_o,
           scl_oen
);
"""


def test_a_port_with_no_direction_keyword_is_reported_as_INFERRED():
    """Read literally, `cmd_ack`, `busy` and `dout` are INPUTS -- a Verilog port
    list carries the last stated direction forward, and the spec was written by
    stripping the `output reg` keywords. They are outputs, and the only place
    that says so is the prose, so the architect has to override the header on
    exactly those names, every run."""
    from eda_agent.contract_linter import prototype_ports

    names, undirected = prototype_ports(DANGLING)
    assert names == ["cmd", "cmd_ack", "busy", "din", "dout", "scl_o", "scl_oen"]
    assert undirected == ["cmd_ack", "busy", "dout", "scl_oen"]


def test_a_prototype_port_missing_from_the_contract_is_an_ERROR():
    from eda_agent.contract_linter import lint_contract_json

    io = [{"name": n, "dir": "input", "width": 1}
          for n in ("cmd", "cmd_ack", "din", "dout", "scl_o", "scl_oen")]
    issues, _ = lint_contract_json(
        json.dumps({"module_name": "i2c", "io": io}), DANGLING)
    errs = [i for i in issues if i.severity == "error" and "busy" in i.message]
    assert errs, [i.message for i in issues]
    warns = [i for i in issues
             if i.severity == "warning" and "no direction" in i.message]
    assert warns and "cmd_ack" in warns[0].message


def test_the_spec_check_is_skipped_when_no_spec_is_given():
    """`lint_contract_json` is called from several places and only one of them
    has the spec; a missing spec must not invent findings."""
    from eda_agent.contract_linter import lint_contract_json

    io = [{"name": "cmd", "dir": "input", "width": 1}]
    issues, _ = lint_contract_json(json.dumps({"module_name": "i2c", "io": io}))
    assert not [i for i in issues if "module header names port" in i.message]


def test_the_architect_is_PRIMED_about_the_ports_it_must_infer():
    """Guidance and gate, the same pairing the oracle prompt uses for inputs.

    The linter catches a DROPPED port after the fact and that is the gate. It
    does not stop a direction being decided wrongly, and its "these were
    inferred" finding is a WARNING -- so it reaches the model only when some
    other error happens to trigger a repair round, and on a clean-but-inferred
    contract it reaches nobody but a human reading `contract_lint.txt`.

    Asserted through `prototype_ports`, which is what the priming is built from:
    on the real i2c header it names exactly the six continuation-line ports, and
    those are the ones the architect re-decides from prose on every run.
    """
    import inspect

    from eda_agent import top_agent
    from eda_agent.contract_linter import prototype_ports

    _, undirected = prototype_ports(DANGLING)
    assert undirected == ["cmd_ack", "busy", "dout", "scl_oen"]

    src = inspect.getsource(top_agent.TopAgent._build_contract_json)
    assert "prototype_ports(spec)" in src, "the priming must be computed"
    assert "primed" in src and "architect.chat(primed" in src, (
        "the primed spec must be what is actually sent")
    assert "authoritative" in src, (
        "it has to say which source wins when the header and the prose "
        "disagree, or naming the ports just restates the ambiguity")


def test_a_header_with_every_direction_stated_primes_nothing():
    """No note when there is nothing to warn about: a spec whose header is
    well formed must produce the same prompt it always did."""
    from eda_agent.contract_linter import prototype_ports

    clean = ("module m (\n    input clk,\n    input a,\n"
             "    output y\n);\n")
    assert prototype_ports(clean)[1] == []
