"""E3: does the `until` field close the largest measured defect in this tree?

Recorded, and the motivation for adding the field: 63% of a2-i2c's 105
requirements name a span in their own text and EVERY ONE was normalised to the
instant its activation began, making every check over one a point check --
"fails every design or passes every design depending only on which way the port
sat at that instant". The over-strict population is 79% that shape and the
vacuous 83%, against 58% of the rest.

The field landed 2026-08-27 14:02-15:31 and a2-i2c ran 2026-08-28 07:07, AFTER,
so no recorded number says whether it took. This is that number.

PRE-REGISTERED. Fires on a small minority => the defect is closed and this
plan's premise is retired; say so plainly rather than defend it. Still fires
broadly => it is the first thing to fix and nothing downstream is interpretable
until it is.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, "/home/user/Veri-Sure")
from specflow.model_io import PortSettings, make_port
from specflow.normalize import _names_a_window, run_normalize_fanout
from specflow.s1_classify import divide_and_classify

OUT = Path("docs/evidence/e3")
SPEC = Path("benchmarks/chipverilog/Des/i2c/i2c_master_bit_ctrl/"
            "description.txt").read_text()

#: The interface, written by hand from the module's declared ports rather than
#: generated by the architect agent. A contract is an interface description, not
#: a design, and skipping that call keeps this measurement to one stage.
CONTRACT = {"module_name": "i2c_master_bit_ctrl", "io": [
    {"name": "clk", "dir": "input", "width": 1},
    {"name": "nReset", "dir": "input", "width": 1},
    {"name": "rst", "dir": "input", "width": 1},
    {"name": "ena", "dir": "input", "width": 1},
    {"name": "clk_cnt", "dir": "input", "width": 16},
    {"name": "cmd", "dir": "input", "width": 4},
    {"name": "din", "dir": "input", "width": 1},
    {"name": "scl_i", "dir": "input", "width": 1},
    {"name": "sda_i", "dir": "input", "width": 1},
    {"name": "cmd_ack", "dir": "output", "width": 1},
    {"name": "busy", "dir": "output", "width": 1},
    {"name": "al", "dir": "output", "width": 1},
    {"name": "dout", "dir": "output", "width": 1},
    {"name": "scl_o", "dir": "output", "width": 1},
    {"name": "scl_oen", "dir": "output", "width": 1},
    {"name": "sda_o", "dir": "output", "width": 1},
    {"name": "sda_oen", "dir": "output", "width": 1},
]}
CONTRACT_JSON = json.dumps(CONTRACT)

port = make_port("api", OUT, None, PortSettings())

units, _results, reqs = divide_and_classify(
    spec=SPEC, contract_json=CONTRACT_JSON, port=port, max_repairs=2)
print(f"S1: {len(units)} units -> {len(reqs)} requirements")
(OUT / "requirements.json").write_text(json.dumps(reqs, indent=2))

windowed = [r for r in reqs if _names_a_window(r.get("text", ""))]
print(f"  requirements naming a span: {len(windowed)} = "
      f"{100*len(windowed)/max(len(reqs),1):.1f}%   (a2-i2c recorded 63%)")

normalized, _nr = run_normalize_fanout(
    requirements=windowed, contract_json=CONTRACT_JSON, contract=CONTRACT,
    port=port, max_repairs=2)
by_uid = {n.req_uid: n for n in normalized}
(OUT / "normalized.json").write_text(json.dumps(
    {u: n.model_dump() for u, n in by_uid.items()}, indent=2, default=str))

#: THE RESIDUAL. A requirement whose text names a span and whose normalized
#: activation still carries no close condition is one the gate warns about and
#: ships anyway.
still = [u for u, n in by_uid.items() if not n.activation.windowed]
print(f"\nRESIDUAL: of {len(by_uid)} windowed requirements that normalized, "
      f"{len(still)} carry NO close condition = "
      f"{100*len(still)/max(len(by_uid),1):.1f}%")
print(f"  closed the window: {len(by_uid) - len(still)}")
print(f"  never normalized at all: {len(windowed) - len(by_uid)}")
json.dump({"units": len(units), "requirements": len(reqs),
           "windowed": len(windowed), "normalized": len(by_uid),
           "still_open": len(still), "uids_still_open": still},
          open(OUT / "e3-result.json", "w"), indent=2)
